name: nmt
channels:
- pytorch
dependencies:
- python=3.6
- anaconda=5.0.1
- plotly=2.1.0
- pylint=1.7.4
- spacy=1.8.2
- tqdm=4.19.2
- pip:
    - torchtext==0.2.0
# From soumith channel
- pytorch=0.3.0
- torchvision=0.2.0
