name: nmt
channels:
    - pytorch
dependencies:
    - python=3.7
    - plotly=3.7.0
    - pylint=2.3.1
    - spacy=2.0.16
    - tqdm=4.31.1
    # from pytorch channel
    - pytorch=1.1.0
    - torchvision=0.2.2
