# Environment with CUDA 8.0 Support
name: nmt
channels:
- soumith
dependencies:
- python=3.6
- anaconda=5.0.0
- plotly=2.0.15
- pylint=1.7.2
- spacy=1.8.2
- tqdm=4.15.0
- pip:
    - keras==2.0.8
    - tensorflow==1.3.0
    - torchtext==0.2.0
# From soumith channel
- pytorch=0.2.0
- torchvision=0.1.9
- magma-cuda80=2.1.0
