name: nmt
channels:
- pytorch
dependencies:
- python=3.6
- plotly=2.2.2
- pylint=1.8.2
- spacy=2.0.5
- tqdm=4.19.4
- pip:
    - torchtext==0.2.3
# From pytorch channel
- pytorch=0.4.0
- torchvision=0.2.0
