# Environment with CUDA 8.0 Support
name: nmt
channels:
- soumith
dependencies:
- python=3.6
- anaconda=5.0.1
- plotly=2.1.0
- pylint=1.7.4
- spacy=1.8.2
- tqdm=4.19.2
- pip:
    - torchtext==0.2.0
# From soumith channel
- pytorch=0.2.0
- torchvision=0.1.9
- magma-cuda80=2.1.0
